### ISSUE TITLE
Add test that executes ipfs binary

### ISSUE THREAD

**Issue by harlantwood** [ipfs/npm-go-ipfs-dep#2]
for example: https://github.com/ipfs/npm-go-ipfs/blob/43d2964358beb142a5d9b97c399d8086c5f1295f/test/index.js

**Comment by diasdavid** [comment]
Now, npm-go-ipfs-dep is a dep of npm-go-ipfs, so that test gets executed for this one, not directly, but pretty close as they get released together :)
