### ISSUE TITLE
Add v0.4.13 support

### ISSUE THREAD

**Issue by paulogr** [ipfs/npm-go-ipfs-dep#22]
Hi !

I've just updated my `go-ipfs` daemon to the version **0.4.13** and I can't use it with `ipfsd-ctl` because the new version was not added to this package.

It is just add the version number to this array ?

https://github.com/ipfs/npm-go-ipfs-dep/blob/fe39e2882ceb498660f41ae2b9d9c31674cf0229/src/check-support.js#L9

Do you accept a PR or have more to change?

Thank you!

**Comment by dryajov** [comment]
We do accept PRs 👍 ! 

There is in fact an outstanding PR to add v0.4.12 support that @diasdavid opened, but it's not merged yet for some reason.

In any case, I don't see any issues opening another PR for v0.4.13.

**Comment by paulogr** [comment]
Now I see why @diasdavid PR doesn't get merged yet.

Since version **0.4.12** there is no more **windows-386** version of the daemon and the tests failed.

Are **windows-386** versions missing? Or will be no more versions to this platform?

Thank you!

**Comment by diasdavid** [comment]
@whyrusleeping @Kubuxu any notes on this one?

**Comment by diasdavid** [comment]
Ping @whyrusleeping @lgierth @Kubuxu, did go-ipfs stop supporting windows?

**Comment by Kubuxu** [comment]
@diasdavid No it didn't. I am not sure why there is no 32-bit build currently on dist but it should be there.

**Comment by diasdavid** [comment]
https://github.com/ipfs/npm-go-ipfs-dep/pull/21

**Comment by diasdavid** [comment]
Hi @paulogr, just released js-ipfsd-ctl v0.26.0 released with go-ipfs 0.4.13 support :)  check it out!

**Comment by paulogr** [comment]
Great news @diasdavid!

Thank you!
