### ISSUE TITLE
Merge into ipfs-shipyard/npm-go-ipfs ?

### ISSUE THREAD

**Issue by achingbrain** [ipfs/npm-go-ipfs-dep#42]
https://github.com/ipfs-shipyard/npm-go-ipfs is very similar to this module, though it has a better name.

They both install a version of `go-ipfs`.  This one exports a `path` function to work out where the `ipfs` binary is and the other one one has a `bin` entry in it's `package.json`.

Is there any reason why they could not be combined?

**Comment by Stebalien** [comment]
`npm-go-ipfs` depends on `npm-go-ipfs-dep`. IIRC, `npm-go-ipfs` specifically exists to install go-ipfs on the local machine with `npm install -g go-ipfs`. `npm-go-ipfs-dep` exists for projects that need to embed go-ipfs but don't want it installed on the local machine.

But I'm not familiar enough with npm to know if this split is really necessary.
