### ISSUE TITLE
Deprecate in favor of npm-go-ipfs

### ISSUE THREAD

**Issue by lidel** [ipfs/npm-go-ipfs-dep#45]
So.. we have two ways of getting go-ipfs via NPM:

- https://www.npmjs.com/package/go-ipfs
- https://www.npmjs.com/package/go-ipfs-dep

Alex fixed a bunch of stuff in https://github.com/ipfs/npm-go-ipfs/pull/26, and stated that [npm-go-ipfs-dep] should be retired. 

Should we deprecate `go-ipfs-dep` and point people at `go-ipfs`?
Any reason for maintaining both?

cc @olizilla @achingbrain @hugomrdias @aschmahmann  @vasco-santos @Gozala @andrew

**Comment by Gozala** [comment]
I don't see any good reason to keep both, but I also have the least context.

**Comment by achingbrain** [comment]
The changes I made to the `go-ipfs` module should make it a drop-in replacement so there's no need for both.

This module should be deprecated with a message saying to use `go-ipfs` and this repo should be archived/moved to the ipfs-inactive org.

See also: https://github.com/ipfs/npm-go-ipfs-dep/issues/42

**Comment by achingbrain** [comment]
I've added a deprecation warning to `go-ipfs-dep` on npm saying to use `go-ipfs` instead and #46 will add a big warning to the README.

If everyone's happy we can merge than and move this repo to `ipfs-inactive`.

**Comment by olizilla** [comment]
Now that the `go-ipfs` dep can do it all, I am very much in favour of derecating and moving to ipfs-inactive. Nice work @achingbrain

**Comment by andrew** [comment]
Quite a few projects have go-ipfs-dep as a dependency, would be good to send them a PR to switch if we're not going to be publishing updates anymore: https://ipfs.ecosystem-dashboard.com/packages/1859?direct=true

**Comment by lidel** [comment]
@andrew has a good point. 

At a very minimum, we need:
- [x] NPM: deprecate https://www.npmjs.com/package/go-ipfs-dep with message that https://www.npmjs.com/package/go-ipfs should be used instead
  - @achingbrain are you able to help with this? I think you mentioned it's deprecated on NPM, but I don't see it. Perhaps deprecation got dismissed when CI published 0.7.0? If you add me as maintainer I can sort this out.

Then,

- [x] Disable CI and move this repo to https://github.com/ipfs-inactive/ and archive it
  - @olizilla do you have perms to do so?


I can help with this if

**Comment by lidel** [comment]
Deprecated on NPM, will move  to https://github.com/ipfs-inactive/ shortly
